version: '3.11'

services:
  web:
    build: .
    command: sh -c "gunicorn HoneyShop.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/HoneyShop
      - static_volume:/usr/src/HoneyShop/static/
      - media_volume:/usr/src/HoneyShop/media/
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.production
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/HoneyShop/static/
      - media_volume:/usr/src/HoneyShop/media/
    ports:
      - "8004:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: