# Generated by Django 4.0.6 on 2022-10-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_first_name', models.CharField(blank=True, max_length=150, verbose_name="Ім'я отримувача")),
                ('recipient_last_name', models.CharField(blank=True, max_length=150, verbose_name='Прізвище отримувача')),
                ('recipient_patronymic', models.CharField(blank=True, max_length=150, verbose_name='По-батькові отримувача')),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефону отримувача')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=6, verbose_name='Будинок')),
                ('flat', models.CharField(blank=True, max_length=5, verbose_name='Квартира')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
