# Generated by Django 4.0.6 on 2022-10-30 13:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='default_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я отримувача"),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище отримувача'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_patronymic',
            field=models.CharField(max_length=100, verbose_name='По-батькові отримувача'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону отримувача'),
        ),
    ]
