# Generated by Django 4.1.2 on 2022-10-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_default_address_default_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-default_address'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреси'},
        ),
    ]
