# Generated by Django 4.1.4 on 2023-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='photos/accounts/%Y/%m', verbose_name='Основна світлина'),
        ),
    ]
