# Generated by Django 4.0.6 on 2022-10-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категорія статті', 'verbose_name_plural': 'Категорії статтей'},
        ),
    ]
