# Generated by Django 4.1.2 on 2022-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('method', models.CharField(choices=[('AFTER', 'Оплата під час отримання товару'), ('PREPAYMENT', 'Передплата'), ('ONLINE', 'Онлайн оплата')], max_length=255, verbose_name='Метод оплати')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Спосіб оплати',
                'verbose_name_plural': 'Способи оплати',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.CharField(default='За тарифами перевізника', max_length=255, verbose_name='Ціна')),
                ('method', models.CharField(choices=[('IN_STORE', 'Самовивіз з магазину'), ('DELIVERY_SERVICE', 'Самовивіз з служби доставки'), ('HOME_DELIVERY', "Кур'єр на вашу адресу")], max_length=255, verbose_name='Метод доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Спосіб доставки',
                'verbose_name_plural': 'Способи доставки',
            },
        ),
    ]
