# Generated by Django 4.1.3 on 2022-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoptions',
            name='method',
            field=models.CharField(choices=[('AFTER', 'Оплата під час отримання товару'), ('ONLINE', 'Онлайн оплата'), ('PREPAYMENT', 'Передплата')], max_length=255, verbose_name='Метод оплати'),
        ),
    ]
