# Generated by Django 4.0.6 on 2022-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Ціна'),
        ),
    ]
