# Generated by Django 4.0.6 on 2022-10-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-available'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
