# Generated by Django 4.1.4 on 2023-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-quantity'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Доступна кількість'),
        ),
    ]
