# Generated by Django 4.1.4 on 2023-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='Характеристика'),
        ),
    ]
