# Generated by Django 4.1.2 on 2022-11-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_product_users_wishlist_alter_review_parent'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_first_name', models.CharField(max_length=100, verbose_name="Ім'я отримувача")),
                ('recipient_last_name', models.CharField(max_length=100, verbose_name='Прізвище отримувача')),
                ('recipient_patronymic', models.CharField(max_length=100, verbose_name='По-батькові отримувача')),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону отримувача')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вулиця')),
                ('house', models.CharField(blank=True, max_length=6, null=True, verbose_name='Будинок')),
                ('flat', models.CharField(blank=True, max_length=5, null=True, verbose_name='Квартира')),
                ('delivery_service_department', models.CharField(blank=True, default=1, max_length=50, verbose_name='Відділення служби доставки')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.paymentoptions', verbose_name='Спосіб оплати')),
                ('billing_status', models.BooleanField(default=False, verbose_name='Здійснено оплату')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('delivery_option', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.deliveryoptions', verbose_name='Спосіб доставки')),
                ('total_price', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Загальна сума оплати')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вартість')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
