# Generated by Django 4.1.3 on 2022-11-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_paymentoptions_method'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.deliveryoptions', verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_service_department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Відділення служби доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Загальна сума оплати'),
        ),
    ]
