# Generated by Django 4.1.4 on 2023-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_service_department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Відділення служби доставки'),
        ),
    ]
